# Generated by Django 4.2.9 on 2024-01-12 14:09

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('image_file', models.ImageField(upload_to=main.models.get_upload_path)),
                ('voice_file', models.FileField(upload_to=main.models.get_upload_path)),
            ],
        ),
    ]
