# Generated by Django 4.2.9 on 2024-01-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='text_content',
            field=models.CharField(max_length=50),
        ),
    ]
