# Generated by Django 3.2.11 on 2024-01-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240118_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='level_m',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='main.levels'),
        ),
    ]
