# Generated by Django 3.2.11 on 2024-01-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_test_level_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='level_m',
        ),
    ]
