# Generated by Django 3.2.11 on 2024-01-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_test_level_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='level',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.levels'),
        ),
    ]
